# Azure Pipelines YAML for backend deployment
trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  # Azure service connection name
  azureServiceConnectionId: 'your-service-connection'
  webAppName: 'skillbridge-api'
  
  # Agent VM image name
  vmImageName: 'ubuntu-latest'

  # Working Directory
  workingDirectory: '$(System.DefaultWorkingDirectory)/backend'

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: BuildJob
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.9'
        displayName: 'Use Python 3.9'

    - script: |
        cd backend
        python -m venv antenv
        source antenv/bin/activate
        pip install setuptools
        pip install -r requirements.txt
      workingDirectory: $(System.DefaultWorkingDirectory)
      displayName: 'Install requirements'

    - task: ArchiveFiles@2
      displayName: 'Archive files'
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)/backend'
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
        replaceExistingArchive: true

    - upload: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
      displayName: 'Upload package'
      artifact: drop
