name: Debug Build Python App

on:
  push:
    branches: [main]

jobs:
  debug:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List backend folder contents
        run: |
          ls -la
          cd backend
          ls -la
